//! Keeps `web/dist` present and fresh for `rust-embed`.
//!
//! Two jobs:
//!
//! 1. **Seed.** `web/dist` is generated by `npm run build` in `web/` and is not
//!    tracked by git, so a clone without node has nothing for `rust-embed` to
//!    embed. When `web/dist/index.html` is missing, the committed
//!    `web/placeholder/index.html` is copied in so `cargo build` works on its
//!    own. An existing build is never overwritten.
//! 2. **Invalidate.** `rust-embed`'s `debug-embed` decides *when* assets are
//!    baked in, not when cargo reconsiders them: the proc macro cannot emit
//!    `cargo:rerun-if-changed`, so without this script a fresh `npm run build`
//!    followed by `cargo run` serves the previously embedded bytes.
//!
//! Directory `rerun-if-changed` tracks the directory's own mtime, which covers
//! files appearing and disappearing but not edits nested under `assets/`. Vite
//! rewrites `index.html` on every build, so that file is tracked by name too.

use std::fs;
use std::path::Path;

fn main() {
    println!("cargo:rerun-if-changed=web/dist");
    println!("cargo:rerun-if-changed=web/dist/index.html");
    println!("cargo:rerun-if-changed=web/placeholder/index.html");

    let dist = Path::new("web/dist");
    let index = dist.join("index.html");
    if index.exists() {
        return;
    }

    let placeholder = Path::new("web/placeholder/index.html");
    if !placeholder.exists() {
        println!("cargo:warning=web/placeholder/index.html is missing; web/dist may be empty");
        return;
    }

    if let Err(err) = fs::create_dir_all(dist).and_then(|()| fs::copy(placeholder, &index)) {
        println!("cargo:warning=could not seed web/dist from the placeholder: {err}");
    }
}
